create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(btrim(name)) between 1 and 120),
  email text not null check (char_length(email) between 3 and 200 and position('@' in email) > 1),
  route text not null check (route in ('craft-culture', 'powder-snow', 'anime-kingdom', 'sanin-setouchi-art', 'tokyo-halloween')),
  message text not null check (char_length(btrim(message)) between 1 and 2000),
  language text not null default 'en' check (char_length(language) between 2 and 10),
  source_path text not null default '/' check (char_length(source_path) between 1 and 300),
  status text not null default 'new' check (status in ('new', 'contacted', 'closed'))
);

alter table public.inquiries enable row level security;

revoke all on table public.inquiries from anon, authenticated;
grant insert on table public.inquiries to anon, authenticated;
grant usage, select on sequence public.inquiries_id_seq to anon, authenticated;

drop policy if exists "public can submit inquiries" on public.inquiries;
create policy "public can submit inquiries"
on public.inquiries
for insert
to anon, authenticated
with check (
  char_length(btrim(name)) between 1 and 120
  and char_length(email) between 3 and 200
  and position('@' in email) > 1
  and route in ('craft-culture', 'powder-snow', 'anime-kingdom', 'sanin-setouchi-art', 'tokyo-halloween')
  and char_length(btrim(message)) between 1 and 2000
  and status = 'new'
);

create index if not exists inquiries_created_at_idx on public.inquiries (created_at desc);

comment on table public.inquiries is 'Public website trip inquiries. Public roles may insert but cannot read rows.';
